name: mycalendar
description: custom app made by capella.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  date_picker_timeline: ^1.1.3
  firebase_database: ^3.1.0
  dropdownfield: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true
