name: mycalendar
description: custom app made by capella.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  date_picker_timeline: ^1.1.3
  firebase_database: ^3.1.0
  dropdownfield: 1.0.0
  bmprogresshud: ^0.0.5
  flutter_masked_text: ^0.8.0

dev_dependencies:
  test:
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true
